name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        run: sudo apt-get update && sudo apt-get install -y clang gcc-arm-none-eabi gcc-multilib

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, clippy, rustfmt

      - name: Install cargo-ledger
        run: cargo install cargo-ledger --git=https://github.com/LedgerHQ/cargo-ledger

      - name: Setup cargo-ledger
        run: cargo ledger setup

      - name: Cargo clippy
        run: cargo clippy --all -- --no-deps -D warnings

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Build app
        run: |
          cargo ledger build nanos
          cargo ledger build nanosplus
          cargo ledger build nanox

      - name: Build app for Speculos
        if: github.event_name == 'push'
        run: cargo ledger build nanosplus -- -F speculos

      - name: Deploy
        if: github.event_name == 'push'
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ansible
          playbook: update-apps.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: ledger.vara.rs
