name: Deploy

on:
  push:
    branches: [master]
  pull_request: # TODO: Remove after debug
    branches: [master]
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually triggered'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: LedgerHQ/speculos

      - name: Install dependencies
        run: >-
          sudo apt-get update && sudo apt install -y
            clang gcc-arm-none-eabi gcc-multilib

      - name: Build `speculos`
        run: |
          cmake -B build/ -S . && cd build
          make openssl
          make launcher
          ls -rvf speculos
