name: Deploy

on:
  pull_request: # TODO: Remove after debug
    branches: [master]
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually triggered'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: LedgerHQ/speculos

      - name: Install dependencies
        run: >-
          sudo apt-get update && sudo apt-get install -y
          python3-pyqt5 python3-construct python3-flask-restful python3-jsonschema
          python3-mnemonic python3-pil python3-pyelftools python3-requests
          qemu-user-static

      - name: Build `speculos`
        run: |
          cmake -B build/ -S . && cd build
          make openssl
          make launcher
          ls -rvf speculos
